### ISSUE TITLE
Date missing on an otherwise great theme

### ISSUE THREAD

**Issue by simplyvinay** [carlcodling/statattack#1]
It would be great if tapping on the time would toggle into a date (Sat January 1)

**Comment by carlcodling** [comment]
Hi Vinay, thanks for the feedback. Unfortunately I've decided to stop supporting further updates to my fitbit clock faces. The fitbit developer platform is horrible to work with so I've opted to put my efforts elsewhere.

**Comment by simplyvinay** [comment]
No problem, I've heard about it being bad as well, which is why I didn't give it a go myself :P
